services:
  regression:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: regression
    ports:
      - 8000:8000
    depends_on:
      - postgresql

  postgresql:
    image: postgres:15.1
    container_name: regression-db
    environment:
      POSTGRES_USER: koloni
      POSTGRES_PASSWORD: test
      POSTGRES_DB: test
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -h localhost -p 5432" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - db-data:/var/lib/postgresql/data



volumes:
  db-data: