[project]
name = "mlops"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.115.12",
    "httpx>=0.28.1",
    "requests>=2.32.3",
    "scikit-learn==1.6.1",
    "uvicorn>=0.34.2",
]
